### ISSUE TITLE
go install doesn't work

### ISSUE THREAD

**Issue by licht1stein** [TheOpenDictionary/odict#1047]
```
❯ go install github.com/TheOpenDictionary/odict@latest
go: finding module for package github.com/TheOpenDictionary/odict/cli
go/pkg/mod/github.com/!the!open!dictionary/odict@v1.23.0/odict.go:7:2: module github.com/TheOpenDictionary/odict@latestfound (v1.23.0), but does not contain package github.com/TheOpenDictionary/odict/cli
```

Fedora 41, go version go1.23.4 linux/amd64

**Comment by Nickersoft** [comment]
Hey @licht1stein! Thanks for opening the issue. I'm fully aware of this – and to be honest, V2's release is right around the corner, which is a ground-up rewrite in Rust. That said, the binaries in the GitHub releases should still continue to work for V1, and you should still be able to install via Homebrew (which should be available on Linux):

```
brew tap TheOpenDictionary/odict
brew install odict
```
