### ISSUE TITLE
Where can ODXML schema specification be found?

### ISSUE THREAD

**Issue by lancioni** [TheOpenDictionary/odict#488]
I can't find anywhere in the documentation website or the GitHub code a specification of the ODXML format. Is any XSD , DTD or other schema available?

**Comment by Nickersoft** [comment]
Hey @lancioni! Thanks for opening an issue. There isn't, currently, though I agree there definitely should be. I'll look into writing/generating a DTD for the current format. In the meantime, the [website](https://www.odict.org/docs/xml) holds all the information currently available about the format.

**Comment by Nickersoft** [comment]
I added a script that will generate a valid XSD given the Go structs that support the ODXML format. Seemed easier than trying to generate structs from an XSD, seeing we have addition JSON tags on the structs and whatnot. It's available in the root of the repository :)

Started #491 to try to add XML validation to the ODict CLI itself, but have run into a bunch of issues trying to cross-compile `libxml2` so put a pin in it for now.
