### ISSUE TITLE
Part of Speech 'abbrev' shows as 'unknown'

### ISSUE THREAD

**Issue by panthia** [TheOpenDictionary/odict#551]
I have tried several of the [Part of Speech Tags](https://www.odict.org/docs/reference/pos) and they work except for 'abbrev' which is showing as unkown when I look up the word.  

────────────────────────────────
A
────────────────────────────────

Test

unknown

   1. abbreviation for apple

`  <entry term="A">
    <ety description="Test" >
      <sense pos="abbrev">
        <definition value="abbreviation for apple" />
      </sense>
    </ety>
  </entry>`

**Comment by Nickersoft** [comment]
Hey @panthia! Thanks for bringing this to my attention. Will check on this and get back to you ASAP.

**Comment by Nickersoft** [comment]
So it turns out this issue also existed for other POS values like `AdjectiveKu` where the binary enum we're using has the name of `adj_ku`, but the label used when compiling dictionaries is `adj-ku`. So it compiles it correctly, but when it tries looking it up in binary it can't find the right value.

Opened a PR to fix it!

**Comment by panthia** [comment]
Thanks for looking into this. It is still not working for me. Here is my test dictionary. 

`<dictionary name="English Wikipedia">
  <entry term="lexicography">
    <ety description="From lexico- (prefix meaning ‘speech; words’) + -graphy (suffix meaning ‘something written about a specified subject’).">
      <sense pos="abv">
          <definition value="The art or craft of compiling, writing, and editing dictionaries.">
            <example>He studied lexicography in college.</example>
          </definition>
      </sense>
    </ety>
  </entry>
</dictionary>`

![Selection_082](https://github.com/TheOpenDictionary/odict/assets/8065771/7b2f251c-558d-46a5-adb8-d0ddefd7f500)

**Comment by Nickersoft** [comment]
Responded in https://github.com/TheOpenDictionary/odict/issues/563
