### ISSUE TITLE
'usage' replaced by 'sense'?

### ISSUE THREAD

**Issue by jowodo** [TheOpenDictionary/odict#556]
When looking at the XML part of the official documentation, it seems that `usage` has been replaced by `sense`. 

I think this needs to be changed here: 
- https://www.odict.org/docs/xml/ety
- https://www.odict.org/docs/reference/pos
- https://www.odict.org/docs/xml/group
- https://www.odict.org/docs/xml/definition

I might have overlooked some spots. 
Again, thanks for this software. It is great!

**Comment by Nickersoft** [comment]
Glad you're liking it! And you're absolutely correct, thanks for catching that! Could have sworn I updated the docs haha.

**Comment by Nickersoft** [comment]
All updated! Thanks again for catching this.
