### ISSUE TITLE
sense ="abv" not working for me. ref #551

### ISSUE THREAD

**Issue by panthia** [TheOpenDictionary/odict#563]
Thanks for looking into this. It is still not working for me. Here is my test dictionary. 

`<dictionary name="English Wikipedia">
  <entry term="lexicography">
    <ety description="From lexico- (prefix meaning ‘speech; words’) + -graphy (suffix meaning ‘something written about a specified subject’).">
      <sense pos="abv">
          <definition value="The art or craft of compiling, writing, and editing dictionaries.">
            <example>He studied lexicography in college.</example>
          </definition>
      </sense>
    </ety>
  </entry>
</dictionary>`

![Selection_082](https://github.com/TheOpenDictionary/odict/assets/8065771/7b2f251c-558d-46a5-adb8-d0ddefd7f500)

_Originally posted by @panthia in https://github.com/TheOpenDictionary/odict/issues/551#issuecomment-1886152131_

**Comment by Nickersoft** [comment]
So sorry about that – I forgot to release a new version! Just landed [1.21.0](https://github.com/TheOpenDictionary/odict/releases/tag/v1.21.0) which includes this fix, so if you upgrade it should work.
