### ISSUE TITLE
Error with Unsupported Directory Import in Node SDK

### ISSUE THREAD

**Issue by Rajanikila** [TheOpenDictionary/odict#738]
I encountered an error while using the Node SDK provided by theopendictionary package which is in the Official Documentation. When running the SDK's Lookup function in my project, I received the following error related to unsupported directory imports:

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/nikila/my-project/node_modules/theopendictionary/dist/__generated__' is not supported resolving ES modules imported from /home/senthil/my-node-project/node_modules/theopendictionary/dist/types.js
This issue seems to be occurring due to directory imports that are not supported within the ES modules used by the theopendictionary package.

Steps to Reproduce:

Initialize the theopendictionary Node SDK in a project.
Execute the Lookup function with specific parameters.
Observe the error related to unsupported directory import.
Expected Behavior:
I expected the Node SDK's Lookup function to execute without errors and provide accurate results for the queried term. However, the error related to unsupported directory imports prevented successful execution.

Environment:

Node.js version: 18.18.2
Package version: theopendictionary . I installed by using command from the offcial docs -> npm install theopendictionary
Additional Information:
I have tried updating Node.js to the latest version (18.18.2) and reinstalling the theopendictionary package, but the issue persists. The error message indicates an issue with unsupported directory imports within ES modules.

Any guidance or updates on resolving this issue would be greatly appreciated

**Comment by Senthil-Bala** [comment]
How to fix this issue ?

**Comment by Nickersoft** [comment]
Fixed by #ff0ec85
