### ISSUE TITLE
Client side (browser) support for Odict without having to use the cli exe

### ISSUE THREAD

**Issue by vinapp** [TheOpenDictionary/odict#98]
Just want to know if there is a way to load and run odict on the client side (Browser). Also, if I need to build an App (Android & iOS) do you expect to have access to shell to execute the lookup/search on the odict ?.

**Comment by maxdemaio** [comment]
ODict does have bindings for NodeJS and Kotlin if you're talking about android development. Not sure on Swift, but the ODict spec can be used in any programming language supported by the FlatBuffer protocol!

**Comment by Nickersoft** [comment]
Hey @vinapp! Thanks for taking the time to check-out ODict. Native JS access to ODict dictionaries is a bridge we'll be crossing at some point soon, and I was thinking we could maybe use WebAssembly in Go for it. As for mobile, it has currently been unexplored, but theoretically you should be able to invoke the CLI from Android or iOS by embedding the CLI as an asset. 

All this said, the ODict specification is an open standard, so you could just use the [schema.fbs](https://github.com/TheOpenDictionary/odict/blob/main/schema.fbs) file with the [FlatBuffer compiler](https://github.com/google/flatbuffers) to generate language-specific code for deserializing the dictionary buffer (it supports JS!). You may have to do some custom read logic, as the file has some header information that needs to be worked around. You would also need to decompress it using Snappy. The Go implementation for this logic is [here](https://github.com/TheOpenDictionary/odict/blob/main/go/read.go).

Originally we were using FFIs to interop with the Go code to prevent code duplication, but thought there'd be less overhead if we just invoked the binary directly (the approach esbuild's JS API uses). FFI requires a lot of boilerplate. The other option is we just natively implement read logic in all languages haha.

We definitely need a better story around this – but I think in the short-term, at least for web, WebAssembly could be a good option. We also welcome contributions!!

**Comment by vinapp** [comment]
Thanks @Nickersoft, on invoking CLI ... Would have been nice if he had some samples around hybrid apps using ionic/angular (Cordova/capacitor) libraries.

Meanwhile Let me check on flatbuffers. I am sure many of them would want it work without CLI.

**Comment by Nickersoft** [comment]
Hey @vinapp! I'm starting to look into a potential WebAssembly port and had a question for you: had would you visualize loading dictionaries? From Blob objects?

**Comment by vinapp** [comment]
Hi @Nickersoft I tried using WebAssembly calling Go code from the JS. It works well. But got into a problem while loading the .odict file .. I used snappy.Decode also tried skipping the header (as suggested) but still didn't work. I can share the sample on what I have tried.

**Comment by Nickersoft** [comment]
Sure, that'd be super helpful! I actually just modularized the codebase so we can only call the Go code we need via WebAssembly without trying to compile modules that can't support WASM (a lot of the Bleve and CLI-specific code). Still need to fiddle with it some more, though. Ideally would like to get an NPM package released at some point.

**Comment by vinapp** [comment]
Great. Yes I tried .. Bleve is not supported Via WASM. Please find the
files attached. I am loading mydictionay.odict from the 'go' code (jsonWrapper
function) and strip off the hearder (as suggested).  Hope this helps. Let
me know if anything is not clear. I can help with testing/coding etc. ..

If this feature is rolled out this will be of great help for the community.
Thanks.

Regards,
Vinod

**Comment by michael-wolfenden** [comment]
@Nickersoft has the `@theopendictionary/wasm` package been published to npm?

**Comment by Nickersoft** [comment]
Hey @michael-wolfenden – I did just land this feature, but I was having a bit of trouble with the publishing. The latest release got added to GitHub, but not of the packages were actually released anywhere. Let me send out a new version and will let you know when it's up 👍🏻

**Comment by michael-wolfenden** [comment]
That makes sense now @Nickersoft, I was wondering why the latest version of `theopendictionary` v0.11.0 wasn't on npm either.

**Comment by Nickersoft** [comment]
Just got everything published! The package is `@theopendictionary/wasm` and is in the release candidate phase. I haven't had time to write up documentation yet, but if you look at the `demo.html` in the `wasm` folder it should give a pretty good idea of how to use the API. Look forward to hearing how it works for you!
